name: Unity Tests (Personal License)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unity-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.0
          personal: true

      - name: Run EditMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.0
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testResults: EditModeResults.xml

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.0
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testResults: PlayModeResults.xml