name: Unity Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unity-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testMode: [editmode, playmode]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.0
          personal: true

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.0
          testMode: ${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testResults: TestResults_${{ matrix.testMode }}.xml
          failOnFailedTests: true
          githubAnnotations: true