name: Unity Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  editmode:
    name: EditMode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/unity
          key: ${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}

      - name: Run EditMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.0
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  playmode:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.0
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}